---
title: "figure 1"
output: html_document
date: "2025-08-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
library(patchwork)
library(readxl)
```

## fig 1a
```{r}
d <- read_excel("Fig. 1.xlsx")
unique(d$Process)
unique(d$Mode)
unique(d$Process)

  
reds <- RColorBrewer::brewer.pal(name = "Reds", n = 9)
scales::show_col(reds)

rdbu <- RColorBrewer::brewer.pal(name = "RdBu", n = 9)
scales::show_col(rdbu)
mycol <- rdbu[c(1:3,4)]


d$Mode2 <- factor(d$Mode,
                  levels = rev(c("Int (CN)",
                           "Int (ZA)",
                             "Ext-1 (CN)",
                             "Ext-2 (CN)",
                             "Ext-3 (CN)",
                             "Ext-4 (CN)",
           
                             "Ext-1 (KR)")))

d$Process2 <- factor(d$Process,
                  levels = c("Infra.&Equip.",
                                 "Energy",
                                 "Transport" ,
                                 "Feed",
                                 "Net carbon footprint"))


mytheme <- 
   theme(legend.key.height = unit(0.5, "line"),
         legend.key.width =  unit(0.6, "line"),
         legend.position = c(1, 0),
         legend.justification = c(1,0),
         legend.background = element_blank()
         )+
   theme(axis.text = element_text(color = "black"))



# Split data by facet
d1 <- d %>% filter(Process != "Net carbon footprint", Species == "Genetically improved")
d2 <- d %>% filter(Process != "Net carbon footprint", Species == "Non-genetically improved")

# Create the first plot
p1 <- ggplot(d1, aes(y = Mode2, x = kgCO2eq, fill = Process2)) +
  geom_col(position = "stack") +
  scale_fill_manual(values = mycol) +
  geom_vline(xintercept = 0, linetype = "solid", linewidth = 0.3) +
  theme_classic() +
  ggtitle("Genetically improved")+
  scale_x_continuous(limits = c(-1000, 12000))+
   labs(x = ~"Carbon footprint (kg CO"[2]~"eq. t"^"-1"*")",
        y = "")  +
  labs(fill = NULL)+
 
  mytheme
   

# Create the second plot
p2 <- ggplot(d2, aes(y = Mode2, x = kgCO2eq, fill = Process2)) +
  geom_col(position = "stack") +
  scale_fill_manual(values = mycol) +
  geom_vline(xintercept = 0, linetype = "solid", linewidth = 0.3) +
  theme_classic() +
  ggtitle("Non-genetically improved")+
   scale_x_continuous(limits = c(-1000, 12000))+
   labs(x = ~"Carbon footprint (kg CO"[2]~"eq. t"^"-1"*")",
         y = "",
        tag = ~bold("a")
        )  +
   guides(fill = "none")+
    labs(fill = NULL)+

  mytheme

# Use patchwork and set relative heights
p_a <- (p2 / p1) +
  plot_layout(heights = c(n_distinct(d2$Mode2), 
                          n_distinct(d1$Mode2)),
              #guides = "collect",
              axis_titles = "collect"
              )

p_a
#ggsave("fig.1a.png", width = 569/90, height = 295/90, dpi = 900)
```

## fig 1b
```{r}
d <- read_excel("Fig. 1.xlsx", sheet = 2, na = "NA")

names(d)
str(d)


d_sub1 <- d %>% 
  filter(Stage == "Grow-out") 
  
d_sub2 <- d %>% 
  filter(Stage == "Hatchery") %>% 
  select(CO2_seed = kgCO2eq)

d_sd <- cbind(d_sub1, d_sub2) %>% 
  mutate(min = ifelse(kgCO2eq > 0, CO2 + CO2_seed - sd, kgCO2eq - sd),
         max = ifelse(kgCO2eq > 0, CO2 + CO2_seed + sd, kgCO2eq + sd)
         ) 



  
paired <- RColorBrewer::brewer.pal(name = "Paired", n = 9)
scales::show_col(paired)


mycol2 <- paired[c(2,1)]

d$Mode <- factor(d$Mode,
                  levels = rev(c("Int (CN)",
                           "Int (ZA)",
                             "Ext-1 (CN)",
                             "Ext-2 (CN)",
                             "Ext-3 (CN)",
                             "Ext-4 (CN)",
           
                             "Ext-1 (KR)")))

d$Stage <- factor(d$Stage,
                  levels = c("Grow-out",
                                 "Hatchery"))


mytheme <- 
   theme(legend.key.height = unit(0.5, "line"),
         legend.key.width =  unit(0.6, "line"),
         legend.position = c(1, 0),
         legend.justification = c(1,0),
          legend.background = element_blank()
         )+
   theme(axis.text = element_text(color = "black"))



# Split data by facet
d1 <- d %>% filter( Species == "Genetically improved")
d2 <- d %>% filter(Species == "Non-genetically improved")

# Create the first plot
p1 <- ggplot(d1, aes(y = Mode, x = kgCO2eq, fill = Stage)) +
  geom_col(position = "stack") +
  

  scale_fill_manual(values = mycol2) +
  geom_vline(xintercept = 0, linetype = "solid", linewidth = 0.3) +
  theme_classic() +
  ggtitle("Genetically improved")+
  scale_x_continuous(limits = c(-1400, 12000))+
   labs(x = ~"Carbon footprint (kg CO"[2]~"eq. t"^"-1"*")",
        y = "")  +
  labs(fill = NULL)+
  mytheme
   
p1
# Create the second plot
p2 <- ggplot(d2, aes(y = Mode, x = kgCO2eq, fill = Stage)) +
  geom_col(position = "stack") +
  scale_fill_manual(values = mycol2) +
  geom_vline(xintercept = 0, linetype = "solid", linewidth = 0.3) +

  theme_classic() +
  ggtitle("Non-genetically improved")+
   scale_x_continuous(limits = c(-1400, 12000))+
   labs(x = ~"Carbon footprint (kg CO"[2]~"eq. t"^"-1"*")",
         y = "",
           tag = ~bold("b"))  +
guides(fill = "none")+
  mytheme

p2
# Use patchwork and set relative heights
p_b <- (p2 / p1) +
  plot_layout(heights = c(n_distinct(d2$Mode), 
                          n_distinct(d1$Mode)),
              #guides = "collect",
              axis_titles = "collect"
              )

p_b
#ggsave("fig.1a.png", width = 569/90, height = 295/90, dpi = 900)
```



## fig 1c
```{r}
d3 <- read_excel("Fig. 1.xlsx", sheet = 3)
unique(d$Process)
unique(d3$Mode)
unique(d$Process)

greens <- RColorBrewer::brewer.pal(name = "Greens", n = 9)
scales::show_col(greens)

rdbu <- RColorBrewer::brewer.pal(name = "RdBu", n = 9)
scales::show_col(rdbu)
mycol3 <- c(greens[7], "grey50")

d3$Mode2 <- factor(d3$Mode,
                   levels = rev(c(
                     "Beef",             
                     "Lamb",           
                     "Pork",     
                     "Chicken",          
                     "Shrimp",
                     "Salmon",    
                     "Int",
                     "Ext-1",
                     "Ext-2",            
                     "Ext-3",            
                     "Ext-4"            
                   )))

mytheme <- 
  theme(legend.key.height = unit(0.7, "line"),
        legend.key.width =  unit(0.7, "line"),
        legend.position = c(1, 0.05),
        legend.justification = c(1,0)
  ) +
  theme(axis.text = element_text(color = "black"))

# Create the plot
p_c <-
  ggplot(d3, aes(y = Mode2, x = kgCO2eq, fill = fill)) +
  theme_classic() +
  geom_col(width = 0.8) +
  scale_fill_manual(values = mycol3) +
  geom_errorbarh(
    
    aes(xmin = kgCO2eq - sd, xmax = kgCO2eq + sd),
    height = 0.2
  ) +
  labs(x = ~"Carbon footprint (kg CO"[2]~"eq. kg protein"^"-1"*")",
       y = "",
       tag = ~bold("c")) +
  labs(fill = NULL) +
  scale_x_continuous(limits = c(-3, 200),
                     expand = expansion(mult = c(0.02, 0.02))
  ) +
  mytheme

p_c
# ggsave("fig.1c.png", width = 569/90, height = 295/90, dpi = 900)

```


```{r}


(p_a | p_b )/p_c 

ggsave("figure1.png", width = 661/90, height = 593/90, dpi = 900)
ggsave("figure1.pdf", width = 661/90, height = 593/90)
```




